export const defaultTheme = {
  colors: {
    'base-white': '#FFFFFF',
    'base-background': '#FAFAFA',
    'base-card': '#F3F2F2',
    'base-input': '#EDEDED',
    'base-button': '#E6E5E5',
    'base-hover': '#D7D5D5',
    'base-label': '#8D8686',
    'base-text': '#574F4D',
    'base-subtitle': '#403937',
    'base-title': '#272221',
    'base-title2': '#ffff',
    'base-error': '#f84747',
    'base-red': '#CC001E',
    'base-red-ce': '#eb525e',
    'brand-red': '#CC001E',
    'brand-red-dark': '#CC001E',
    'brand-red-darkk': '#9b0000',
    'brand-red-ce': '#eb525e',
    'brand-red-light': '#FFE0E5',
    'brand-purple-light': '#EBE5F9',
    'brand-yellow-dark': '#C47F17',
    'brand-yellow': '#DBAC2C',
    'brand-yellow-light': '#F1E9C9',
  },
  textSizes: {
    'title-title-xl': '3rem',
    'title-title-l': '2rem',
    'title-title-m': '1.5rem',
    'title-title-s': '1.2rem',
    'title-title-xs': '1.125rem',
    'text-regular-l': '1.25rem',
    'text-bold-l': '1.25rem',
    'text-regular-m': '1rem',
    'text-bold-m': '1rem',
    'text-regular-s': '0.875rem',
    'text-bold-s': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-button-s': '0.75rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
};
